name: Testing

on:
  push:
    branches: [ master, '*.build' ]
  pull_request:

  workflow_dispatch:


jobs:

  test_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          brew install \
            cmake \
            arpack \
            openblas \
            lapack \
            superlu \
            suite-sparse
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Build
        run: |
          cd build
          make install

          
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
            build-essential \
            cmake \
            libarpack2-dev \
            libblas-dev \
            liblapack-dev \
            libsuperlu-dev \
            libf2c2-dev \
            libsuitesparse-dev
      - name: Configure
        run: |
          export CC=gcc
          mkdir build
          cd build
          cmake ..
      - name: Build
        run: |
          cd build
          make install

  test_windows:
    runs-on: windows-2019
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          vcpkg install blas
          vcpkg install clapack
          vcpkg install superlu
          vcpkg install suitesparse
          vcpkg integrate install
      - name: Cache vcpkg packages
        uses: actions/cache@v2
        env:
          cache-name: cache-vcpkg
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          path: |
              C:\vcpkg
      - name: Configure
        env:
          CMAKE_PREFIX_PATH: 'C:\vcpkg\installed\x86-windows'
        run: |
          mkdir -p build\Release
          cd build
          echo $CMAKE_PREFIX_PATH
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_TESTING=ON -DENABLE_TESTS=ON -DBUILD_SHARED_LIBS=OFF -DENABLE_VERBOSE_DEBUG=ON -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 16 2019" -A x64 ..
      - name: Build
        run: |
          cd build
          cmake --build . --config Release --parallel 1 --target install
